// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hellworld2.proto

package hellworld2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hellworld2 service

func NewHellworld2Endpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hellworld2 service

type Hellworld2Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hellworld2_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Hellworld2_PingPongService, error)
}

type hellworld2Service struct {
	c    client.Client
	name string
}

func NewHellworld2Service(name string, c client.Client) Hellworld2Service {
	return &hellworld2Service{
		c:    c,
		name: name,
	}
}

func (c *hellworld2Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Hellworld2.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellworld2Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hellworld2_StreamService, error) {
	req := c.c.NewRequest(c.name, "Hellworld2.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &hellworld2ServiceStream{stream}, nil
}

type Hellworld2_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type hellworld2ServiceStream struct {
	stream client.Stream
}

func (x *hellworld2ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *hellworld2ServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellworld2ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellworld2ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellworld2ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hellworld2Service) PingPong(ctx context.Context, opts ...client.CallOption) (Hellworld2_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Hellworld2.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &hellworld2ServicePingPong{stream}, nil
}

type Hellworld2_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type hellworld2ServicePingPong struct {
	stream client.Stream
}

func (x *hellworld2ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *hellworld2ServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *hellworld2ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellworld2ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellworld2ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *hellworld2ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hellworld2 service

type Hellworld2Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Hellworld2_StreamStream) error
	PingPong(context.Context, Hellworld2_PingPongStream) error
}

func RegisterHellworld2Handler(s server.Server, hdlr Hellworld2Handler, opts ...server.HandlerOption) error {
	type hellworld2 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Hellworld2 struct {
		hellworld2
	}
	h := &hellworld2Handler{hdlr}
	return s.Handle(s.NewHandler(&Hellworld2{h}, opts...))
}

type hellworld2Handler struct {
	Hellworld2Handler
}

func (h *hellworld2Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Hellworld2Handler.Call(ctx, in, out)
}

func (h *hellworld2Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Hellworld2Handler.Stream(ctx, m, &hellworld2StreamStream{stream})
}

type Hellworld2_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type hellworld2StreamStream struct {
	stream server.Stream
}

func (x *hellworld2StreamStream) Close() error {
	return x.stream.Close()
}

func (x *hellworld2StreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellworld2StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellworld2StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellworld2StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *hellworld2Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Hellworld2Handler.PingPong(ctx, &hellworld2PingPongStream{stream})
}

type Hellworld2_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type hellworld2PingPongStream struct {
	stream server.Stream
}

func (x *hellworld2PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *hellworld2PingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellworld2PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellworld2PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellworld2PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *hellworld2PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
